# Script Arguments
dataset_dir: ./dataset/topiocqa-oqf-union/bm25/dpo/random
model_name_or_path: ./results/topiocqa/llama2-7b/oqf-union-bm25/sft_from_qe
output_dir: results/topiocqa/llama2-7b/oqf-union-bm25/dpo/random
num_train_epochs: 3
beta: 0.1

n_toy: -1
eval_split: "test"
chat: false

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
do_eval: false
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: llama2-7b-dpo-full
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
optim: rmsprop
per_device_train_batch_size: 20
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "no"
save_total_limit: null
seed: 42
warmup_ratio: 0.1